/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See LICENSE in the project root for
 * license information.
 */
package com.spring.data.gremlin.common.domain;

import com.spring.data.gremlin.annotation.GeneratedValue;
import com.spring.data.gremlin.annotation.Vertex;
import com.spring.data.gremlin.common.TestConstants;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Vertex(label = TestConstants.VERTEX_PERSON_LABEL)
public class Person {

    @Id
    @GeneratedValue
    private String id;  // Auto-generated by JanusGraph (converted from Long to String)

    private String name;
}
