/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See LICENSE in the project root for
 * license information.
 */
package com.spring.data.gremlin.common.domain;

import com.spring.data.gremlin.annotation.Edge;
import com.spring.data.gremlin.annotation.EdgeFrom;
import com.spring.data.gremlin.annotation.EdgeTo;
import com.spring.data.gremlin.annotation.GeneratedValue;
import com.spring.data.gremlin.common.TestConstants;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@Data
@NoArgsConstructor
@Edge(label = TestConstants.EDGE_RELATIONSHIP_LABEL)
public class Relationship {

    @Id
    @GeneratedValue
    private String id;  // Auto-generated by JanusGraph (converted from String to String)

    private String name;

    private String location;

    @EdgeFrom
    private Person person;

    @EdgeTo
    private Project project;

    public Relationship(String name, String location, Person person, Project project) {
        this.name = name;
        this.location = location;
        this.person = person;
        this.project = project;
        // ID will be auto-generated by JanusGraph
    }

    public Person getPerson() {
        return person;
    }

    public void setPerson(Person person) {
        this.person = person;
    }

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }
}
